package POSPackage;

public class GeneratePOS {
    public GeneratePOS(POS planOfStudy) {
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("|                             PLAN OF STUDY                             | %n");
        System.out.format("|                                                                       | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| NAME:           | STUDENT ID#:    | MAJOR:          | CURRENT DATE:   | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| FALL QUARTER    | WINTER QUARTER  | SPRING QUARTER  | SUMMER QUARTER  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.displayAcademicYear0();
//        System.out.format("|                                2015-2016                              | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display();
        planOfStudy.display1();
        planOfStudy.display2();
        planOfStudy.display3();
        planOfStudy.display4();
        planOfStudy.display5();
        planOfStudy.display6();
        planOfStudy.display7();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.displayAcademicYear1();
//        System.out.format("|                                2016-2017                              | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display20();
        planOfStudy.display21();
        planOfStudy.display22();
        planOfStudy.display23();
        planOfStudy.display24();
        planOfStudy.display25();
        planOfStudy.display26();
        planOfStudy.display27();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2018-2019                              | %n");
        planOfStudy.displayAcademicYear2();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display30();
        planOfStudy.display31();
        planOfStudy.display32();
        planOfStudy.display33();
        planOfStudy.display34();
        planOfStudy.display35();
        planOfStudy.display36();
        planOfStudy.display37();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2018-2019                              | %n");
        planOfStudy.displayAcademicYear3();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display40();
        planOfStudy.display41();
        planOfStudy.display42();
        planOfStudy.display43();
        planOfStudy.display44();
        planOfStudy.display45();
        planOfStudy.display46();
        planOfStudy.display47();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2019-2020                              | %n");
        planOfStudy.displayAcademicYear4();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display50();
        planOfStudy.display51();
        planOfStudy.display52();
        planOfStudy.display53();
        planOfStudy.display54();
        planOfStudy.display55();
        planOfStudy.display56();
        planOfStudy.display57();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("|                                       TOTAL GRADUATION CREDITS:       | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
    }

    public GeneratePOS(POS planOfStudy, String totalCredits) {
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("|                             PLAN OF STUDY                             | %n");
        System.out.format("|                                                                       | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| NAME:           | STUDENT ID#:    | MAJOR:          | CURRENT DATE:   | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| FALL QUARTER    | WINTER QUARTER  | SPRING QUARTER  | SUMMER QUARTER  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.displayAcademicYear0();
//        System.out.format("|                                2015-2016                              | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display();
        planOfStudy.display1();
        planOfStudy.display2();
        planOfStudy.display3();
        planOfStudy.display4();
        planOfStudy.display5();
        planOfStudy.display6();
        planOfStudy.display7();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.displayAcademicYear1();
//        System.out.format("|                                2016-2017                              | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display20();
        planOfStudy.display21();
        planOfStudy.display22();
        planOfStudy.display23();
        planOfStudy.display24();
        planOfStudy.display25();
        planOfStudy.display26();
        planOfStudy.display27();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2018-2019                              | %n");
        planOfStudy.displayAcademicYear2();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display30();
        planOfStudy.display31();
        planOfStudy.display32();
        planOfStudy.display33();
        planOfStudy.display34();
        planOfStudy.display35();
        planOfStudy.display36();
        planOfStudy.display37();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2018-2019                              | %n");
        planOfStudy.displayAcademicYear3();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display40();
        planOfStudy.display41();
        planOfStudy.display42();
        planOfStudy.display43();
        planOfStudy.display44();
        planOfStudy.display45();
        planOfStudy.display46();
        planOfStudy.display47();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
//        System.out.format("|                                2019-2020                              | %n");
        planOfStudy.displayAcademicYear4();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        planOfStudy.display50();
        planOfStudy.display51();
        planOfStudy.display52();
        planOfStudy.display53();
        planOfStudy.display54();
        planOfStudy.display55();
        planOfStudy.display56();
        planOfStudy.display57();
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("| total credits:  | total credits:  | total credits:  | total credits:  | %n");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
        System.out.format("|                                 TOTAL GRADUATION CREDITS:       ");
        System.out.println(totalCredits+" |");
        System.out.format("+-----------------+-----------------+-----------------+-----------------+%n");
    }
}